// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal.proto

package internal

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Job_StatusType int32

const (
	Job_QUEUED    Job_StatusType = 0
	Job_RUNNING   Job_StatusType = 1
	Job_COMPLETED Job_StatusType = 2
	Job_ERROR     Job_StatusType = 3
)

var Job_StatusType_name = map[int32]string{
	0: "QUEUED",
	1: "RUNNING",
	2: "COMPLETED",
	3: "ERROR",
}
var Job_StatusType_value = map[string]int32{
	"QUEUED":    0,
	"RUNNING":   1,
	"COMPLETED": 2,
	"ERROR":     3,
}

func (x Job_StatusType) String() string {
	return proto.EnumName(Job_StatusType_name, int32(x))
}
func (Job_StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_internal_de24136195d2230b, []int{3, 0}
}

type RunDetails struct {
	QueueTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=queue_time,json=queueTime,proto3" json:"queue_time,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Error                string               `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *RunDetails) Reset()         { *m = RunDetails{} }
func (m *RunDetails) String() string { return proto.CompactTextString(m) }
func (*RunDetails) ProtoMessage()    {}
func (*RunDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_de24136195d2230b, []int{0}
}
func (m *RunDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunDetails.Unmarshal(m, b)
}
func (m *RunDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunDetails.Marshal(b, m, deterministic)
}
func (dst *RunDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunDetails.Merge(dst, src)
}
func (m *RunDetails) XXX_Size() int {
	return xxx_messageInfo_RunDetails.Size(m)
}
func (m *RunDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_RunDetails.DiscardUnknown(m)
}

var xxx_messageInfo_RunDetails proto.InternalMessageInfo

func (m *RunDetails) GetQueueTime() *timestamp.Timestamp {
	if m != nil {
		return m.QueueTime
	}
	return nil
}

func (m *RunDetails) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *RunDetails) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *RunDetails) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type RScript struct {
	RPath                string            `protobuf:"bytes,1,opt,name=r_path,json=rPath,proto3" json:"r_path,omitempty"`
	WorkDir              string            `protobuf:"bytes,2,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	RscriptPath          string            `protobuf:"bytes,3,opt,name=rscript_path,json=rscriptPath,proto3" json:"rscript_path,omitempty"`
	Renv                 map[string]string `protobuf:"bytes,4,rep,name=renv,proto3" json:"renv,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *RScript) Reset()         { *m = RScript{} }
func (m *RScript) String() string { return proto.CompactTextString(m) }
func (*RScript) ProtoMessage()    {}
func (*RScript) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_de24136195d2230b, []int{1}
}
func (m *RScript) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RScript.Unmarshal(m, b)
}
func (m *RScript) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RScript.Marshal(b, m, deterministic)
}
func (dst *RScript) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RScript.Merge(dst, src)
}
func (m *RScript) XXX_Size() int {
	return xxx_messageInfo_RScript.Size(m)
}
func (m *RScript) XXX_DiscardUnknown() {
	xxx_messageInfo_RScript.DiscardUnknown(m)
}

var xxx_messageInfo_RScript proto.InternalMessageInfo

func (m *RScript) GetRPath() string {
	if m != nil {
		return m.RPath
	}
	return ""
}

func (m *RScript) GetWorkDir() string {
	if m != nil {
		return m.WorkDir
	}
	return ""
}

func (m *RScript) GetRscriptPath() string {
	if m != nil {
		return m.RscriptPath
	}
	return ""
}

func (m *RScript) GetRenv() map[string]string {
	if m != nil {
		return m.Renv
	}
	return nil
}

type RScriptResult struct {
	Output               string   `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	ExitCode             int32    `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RScriptResult) Reset()         { *m = RScriptResult{} }
func (m *RScriptResult) String() string { return proto.CompactTextString(m) }
func (*RScriptResult) ProtoMessage()    {}
func (*RScriptResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_de24136195d2230b, []int{2}
}
func (m *RScriptResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RScriptResult.Unmarshal(m, b)
}
func (m *RScriptResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RScriptResult.Marshal(b, m, deterministic)
}
func (dst *RScriptResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RScriptResult.Merge(dst, src)
}
func (m *RScriptResult) XXX_Size() int {
	return xxx_messageInfo_RScriptResult.Size(m)
}
func (m *RScriptResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RScriptResult.DiscardUnknown(m)
}

var xxx_messageInfo_RScriptResult proto.InternalMessageInfo

func (m *RScriptResult) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func (m *RScriptResult) GetExitCode() int32 {
	if m != nil {
		return m.ExitCode
	}
	return 0
}

type Job struct {
	Id                   uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               Job_StatusType `protobuf:"varint,2,opt,name=status,proto3,enum=internal.Job_StatusType" json:"status,omitempty"`
	RunDetails           *RunDetails    `protobuf:"bytes,3,opt,name=run_details,json=runDetails,proto3" json:"run_details,omitempty"`
	Context              string         `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Rscript              *RScript       `protobuf:"bytes,5,opt,name=rscript,proto3" json:"rscript,omitempty"`
	Result               *RScriptResult `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_de24136195d2230b, []int{3}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Job) GetStatus() Job_StatusType {
	if m != nil {
		return m.Status
	}
	return Job_QUEUED
}

func (m *Job) GetRunDetails() *RunDetails {
	if m != nil {
		return m.RunDetails
	}
	return nil
}

func (m *Job) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *Job) GetRscript() *RScript {
	if m != nil {
		return m.Rscript
	}
	return nil
}

func (m *Job) GetResult() *RScriptResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*RunDetails)(nil), "internal.RunDetails")
	proto.RegisterType((*RScript)(nil), "internal.RScript")
	proto.RegisterMapType((map[string]string)(nil), "internal.RScript.RenvEntry")
	proto.RegisterType((*RScriptResult)(nil), "internal.RScriptResult")
	proto.RegisterType((*Job)(nil), "internal.Job")
	proto.RegisterEnum("internal.Job_StatusType", Job_StatusType_name, Job_StatusType_value)
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_internal_de24136195d2230b) }

var fileDescriptor_internal_de24136195d2230b = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x6f, 0xd3, 0x30,
	0x18, 0xc6, 0x49, 0xd2, 0x24, 0xcd, 0x1b, 0x36, 0x05, 0x6b, 0x40, 0xe8, 0x0e, 0x94, 0x9c, 0x2a,
	0x21, 0xa5, 0xa8, 0x68, 0xe2, 0xcf, 0x85, 0xc3, 0x12, 0x21, 0x26, 0xe8, 0x86, 0xd7, 0x9e, 0xa3,
	0xb4, 0x31, 0x5b, 0xb4, 0xcc, 0x0e, 0x8e, 0x5d, 0xd6, 0x4f, 0xc6, 0x57, 0xe0, 0xc6, 0x57, 0x42,
	0x71, 0x9c, 0x16, 0x69, 0x87, 0xdd, 0xf2, 0xbc, 0x7e, 0x7e, 0x4f, 0xfc, 0xbe, 0x7e, 0xe1, 0xb0,
	0xa4, 0x82, 0x70, 0x9a, 0x57, 0x71, 0xcd, 0x99, 0x60, 0x68, 0xd8, 0xeb, 0xd1, 0xcb, 0x2b, 0xc6,
	0xae, 0x2a, 0x32, 0x55, 0xf5, 0x95, 0xfc, 0x31, 0x15, 0xe5, 0x2d, 0x69, 0x44, 0x7e, 0x5b, 0x77,
	0xd6, 0xe8, 0xaf, 0x01, 0x80, 0x25, 0x4d, 0x88, 0xc8, 0xcb, 0xaa, 0x41, 0x1f, 0x00, 0x7e, 0x4a,
	0x22, 0x49, 0xd6, 0xfa, 0x42, 0x63, 0x6c, 0x4c, 0xfc, 0xd9, 0x28, 0xee, 0x42, 0xe2, 0x3e, 0x24,
	0x5e, 0xf4, 0x21, 0xd8, 0x53, 0xee, 0x56, 0xb7, 0x68, 0x23, 0x72, 0x2e, 0x3a, 0xd4, 0x7c, 0x18,
	0x55, 0x6e, 0x85, 0x9e, 0xc0, 0x90, 0xd0, 0xa2, 0x03, 0xad, 0x07, 0x41, 0x97, 0xd0, 0x42, 0x61,
	0x47, 0x60, 0x13, 0xce, 0x19, 0x0f, 0x07, 0x63, 0x63, 0xe2, 0xe1, 0x4e, 0x44, 0x7f, 0x0c, 0x70,
	0xf1, 0xe5, 0x9a, 0x97, 0xb5, 0x40, 0x4f, 0xc1, 0xe1, 0x59, 0x9d, 0x8b, 0x6b, 0xd5, 0x8a, 0x87,
	0x6d, 0x7e, 0x91, 0x8b, 0x6b, 0xf4, 0x02, 0x86, 0xbf, 0x18, 0xbf, 0xc9, 0x8a, 0x92, 0xab, 0x8b,
	0x7a, 0xd8, 0x6d, 0x75, 0x52, 0x72, 0xf4, 0x0a, 0x1e, 0xf3, 0x46, 0xc1, 0x1d, 0x67, 0xa9, 0x63,
	0x5f, 0xd7, 0x14, 0x3d, 0x85, 0x01, 0x27, 0x74, 0x13, 0x0e, 0xc6, 0xd6, 0xc4, 0x9f, 0x1d, 0xc7,
	0xbb, 0xe1, 0xeb, 0xbf, 0xc6, 0x98, 0xd0, 0x4d, 0x4a, 0x05, 0xdf, 0x62, 0x65, 0x1c, 0xbd, 0x03,
	0x6f, 0x57, 0x42, 0x01, 0x58, 0x37, 0x64, 0xab, 0xef, 0xd3, 0x7e, 0xb6, 0x6d, 0x6c, 0xf2, 0x4a,
	0x12, 0x7d, 0x95, 0x4e, 0x7c, 0x34, 0xdf, 0x1b, 0x51, 0x02, 0x07, 0x3a, 0x13, 0x93, 0x46, 0x56,
	0x02, 0x3d, 0x03, 0x87, 0x49, 0x51, 0x4b, 0xa1, 0x79, 0xad, 0xd0, 0x31, 0x78, 0xe4, 0xae, 0x14,
	0xd9, 0x9a, 0x15, 0x5d, 0x8c, 0x8d, 0x87, 0x6d, 0xe1, 0x94, 0x15, 0x24, 0xfa, 0x6d, 0x82, 0x75,
	0xc6, 0x56, 0xe8, 0x10, 0xcc, 0xb2, 0x50, 0xe0, 0x00, 0x9b, 0x65, 0x81, 0xde, 0x80, 0xd3, 0x88,
	0x5c, 0xc8, 0x46, 0x11, 0x87, 0xb3, 0x70, 0xdf, 0xc9, 0x19, 0x5b, 0xc5, 0x97, 0xea, 0x6c, 0xb1,
	0xad, 0x09, 0xd6, 0x3e, 0x74, 0x02, 0x3e, 0x97, 0x34, 0x2b, 0xba, 0x65, 0xd1, 0x4f, 0x75, 0xf4,
	0xdf, 0x00, 0x76, 0x8b, 0x84, 0x81, 0xef, 0x97, 0x2a, 0x04, 0x77, 0xcd, 0xa8, 0x20, 0x77, 0x42,
	0xbf, 0x54, 0x2f, 0xd1, 0x6b, 0x70, 0xf5, 0x64, 0x43, 0x5b, 0x85, 0x3d, 0xb9, 0x37, 0x4d, 0xdc,
	0x3b, 0xd0, 0x14, 0x1c, 0xae, 0xc6, 0x10, 0x3a, 0xca, 0xfb, 0xfc, 0xbe, 0x57, 0x1d, 0x63, 0x6d,
	0x8b, 0x3e, 0x01, 0xec, 0x9b, 0x40, 0x00, 0xce, 0xf7, 0x65, 0xba, 0x4c, 0x93, 0xe0, 0x11, 0xf2,
	0xc1, 0xc5, 0xcb, 0xf9, 0xfc, 0xcb, 0xfc, 0x73, 0x60, 0xa0, 0x03, 0xf0, 0x4e, 0xcf, 0xbf, 0x5d,
	0x7c, 0x4d, 0x17, 0x69, 0x12, 0x98, 0xc8, 0x03, 0x3b, 0xc5, 0xf8, 0x1c, 0x07, 0xd6, 0xca, 0x51,
	0xdb, 0xf7, 0xf6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0xe2, 0xa7, 0x4e, 0x60, 0x03, 0x00,
	0x00,
}
